name: injil_cli
description: My new Dart CLI package
version: 0.0.4
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  mason_logger: ^0.2.16
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  inj:
